export const russianCities = [
    { name: "Абакан", slug: "abakan" },
    { name: "Ангарск", slug: "angarsk" },
    { name: "Архангельск", slug: "arkhangelsk" },
    { name: "Астрахань", slug: "astrakhan" },
    { name: "Балашиха", slug: "balashikha" },
    { name: "Барнаул", slug: "barnaul" },
    { name: "Бахчисарай", slug: "bakhchisaray" },
    { name: "Белгород", slug: "belgorod" },
    { name: "Благовещенск", slug: "blagoveshchensk" },
    { name: "Видное", slug: "vidnoye" },
    { name: "Владимир", slug: "vladimir" },
    { name: "Волгоград", slug: "volgograd" },
    { name: "Волжский", slug: "volzhskiy" },
    { name: "Воронеж", slug: "voronezh" },
    { name: "Домодедово", slug: "domodedovo" },
    { name: "Екатеринбург", slug: "yekaterinburg" },
    { name: "Иваново", slug: "ivanovo" },
    { name: "Ижевск", slug: "izhevsk" },
    { name: "Иркутск", slug: "irkutsk" },
    { name: "Йошкар-Ола", slug: "yoshkar-ola" },
    { name: "Казань", slug: "kazan" },
    { name: "Калининград", slug: "kaliningrad" },
    { name: "Калуга", slug: "kaluga" },
    { name: "Кемерово", slug: "kemerovo" },
    { name: "Киров", slug: "kirov" },
    { name: "Краснодар", slug: "krasnodar" },
    { name: "Красноярск", slug: "krasnoyarsk" },
    { name: "Курск", slug: "kursk" },
    { name: "Магнитогорск", slug: "magnitogorsk" },
    { name: "Москва", slug: "moscow" },
    { name: "Мурино", slug: "murino" },
    { name: "Мурманск", slug: "murmansk" },
    { name: "Мытищи", slug: "mytishchi" },
    { name: "Набережные Челны", slug: "naberezhnye-chelny" },
    { name: "Нефтекамск", slug: "neftekamsk" },
    { name: "Нижний Новгород", slug: "nizhny-novgorod" },
    { name: "Новокузнецк", slug: "novokuznetsk" },
    { name: "Новосибирск", slug: "novosibirsk" },
    { name: "Омск", slug: "omsk" },
    { name: "Оренбург", slug: "orenburg" },
    { name: "Пенза", slug: "penza" },
    { name: "Пермь", slug: "perm" },
    { name: "Подольск", slug: "podolsk" },
    { name: "Псков", slug: "pskov" },
    { name: "Ростов-на-Дону", slug: "rostov-na-donu" },
    { name: "Рязань", slug: "ryazan" },
    { name: "Самара", slug: "samara" },
    { name: "Санкт-Петербург", slug: "saint-petersburg" },
    { name: "Саранск", slug: "saransk" },
    { name: "Саратов", slug: "saratov" },
    { name: "Севастополь", slug: "sevastopol" },
    { name: "Симферополь", slug: "simferopol" },
    { name: "Смоленск", slug: "smolensk" },
    { name: "Тюмень", slug: "tyumen" },
    { name: "Улан-Удэ", slug: "ulan-ude" },
    { name: "Уфа", slug: "ufa" },
    { name: "Челябинск", slug: "chelyabinsk" },
    { name: "Ялта", slug: "yalta" },
    { name: "Ярославль", slug: "yaroslavl" }
];

export default russianCities;
